apiVersion: v1
kind: Service
metadata:
  name: metaphactory
  annotations:
#    service.beta.kubernetes.io/aws-load-balancer-ssl-cert: "arn:aws:acm:us-west-2:XXXXXXXX:certificate/XXXXXX-XXXXXXX-XXXXXXX-XXXXXXXX"
#    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: "http"
#    service.beta.kubernetes.io/aws-load-balancer-ssl-ports: "443"
#    service.beta.kubernetes.io/aws-load-balancer-connection-idle-timeout: "60"
spec:
  ports:
  - name: http
    port: 80
    targetPort: 8080
#  - name: https
#    port: 443
#    targetPort: 8080
  selector:
    app: metaphactory
  type: LoadBalancer
  # this is for HA use-cases
#  sessionAffinity: ClientIP